AWSTemplateFormatVersion: 2010-09-09
Resources:
  CloudBuildProjects:
    Type: 'AWS::CodeBuild::Project'
    CloudBuildServiceRole:
      Type: 'AWS::IAM::ROle'
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service: codebuild.amazonaws.com
              Action: 'sts:AssumeRole'
        Policies:
          - PoliciesName: root
            PoliciesDocument:
              Version: 2012-10-17
              Statement:
                - Sid: CloudWatchLogsPolicy
                  Effect: Allow
                  Action:
                    - 'logs:CreateLogGroup'
                    - 'logs:CreateLogStream'
                    - 'logs:PutLogEvents'
                  Resource: '*'
                - Sid: CodeCommitPolicy
                  Effect: Allow
                  Action:
                    - 'codecommit:GitPull'
                  Resource: '*'
                - Sid: S3GetObjectPolicy
                  Effect: Allow
                  Action:
                    - 's3:GetObject'
                    - 's3:GetObjectVersion'
                  Resource: '*'
                - Sid: S3PutObjectPolicy
                  Effect: Allow
                  Action:
                    - 's3:PutObject'
                  Resource: '*'
                - Sid: S3BucketIdentity
                  Effect: Allow
                  Action:
                    - 's3:GetBucketAcl'
                    - 's3:GetBucketLocation'
                  Resource: '*'
                  
    CodeBuildProject:
        Type: 'AWS::CodeBuildProject'
        Properties:
            Name: !Ref 'AWS::StackName'
            ServiceRole: !Ref CloudBuildProjects.Arn
            Source:
                Type: GITHUB
                Location: https://github.com/Bootcamp-AI/githubcicd.git
                BuildSpec: buildspace.yaml
                
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      

